### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by vitananmina67** [codeuk/discord-rat#5]
Runing on Kali.

when i run make Makefile all i get the folowing error:

└─$  make Makefile all
make: Nothing to be done for 'Makefile'.
[1/5] Compiling MacOS binary...
[1/5] Compressing MacOS binary...
bin/upx.exe bin/macos-agent
bin/upx.exe: 1: MZ����@���: not found
bin/upx.exe: 2: Syntax error: "(" unexpected
make: *** [Makefile:20: agent-mac] Error 2

Thanks in advance

**Comment by codeuk** [comment]
Pretty sure this is just a simple mistake I made as I've been testing the Makefile on a Kali WSL... I'll test it on a real Kali machine and see what I can do to fix it 👍

**Comment by vitananmina67** [comment]
thanks sir

**Comment by codeuk** [comment]
I've implemented a fix, let me know if it's working on your end.

**Comment by vitananmina67** [comment]
yes indeed it works, thank you.

**Comment by codeuk** [comment]
no problem, thanks for using the program.
